version: "3"

services:
  front:
    container_name: front
    image: node:16-alpine
    working_dir: /app
    command: yarn start
    volumes:
      - "./front:/app"
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - chatminou_network

  back:
    container_name: back
    image: node:16-alpine
    command: yarn start:dev
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - "./back:/app"
    networks:
      - chatminou_network

networks:
  chatminou_network:
