version: "3"

services:
  front:
    container_name: front
    image: node:16-alpine
    env_file: ./dashboard_front/.env
    working_dir: /app
    command: yarn start
    volumes:
      - "./front:/app"
    ports:
      - "3000:3000"
    depends_on:
      - back
